### ISSUE TITLE
Decorators for MobX put on separate lines

### ISSUE THREAD

**Issue by houshuang** [jlongster/prettier#325]
I understand that class decorators are usually put on their own line above the class, however the standard style with MobX annotations within a class is to put them on the same line as what they annotate. [Example](https://mobx.js.org/refguide/observable-decorator.html):

![screen shot 2017-01-19 at 15 25 22](https://cloud.githubusercontent.com/assets/61575/22110313/88ee7406-de5b-11e6-9121-ab2938885b87.png)

Currently prettier splits all the lines that have decorators, making it look very messy.

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22import%20%7Bobservable%7D%20from%20%5C%22mobx%5C%22%3B%5Cn%5Cnclass%20OrderLine%20%7B%5Cn%20%20%20%20%40observable%20price%3Anumber%20%3D%200%3B%5Cn%20%20%20%20%40observable%20amount%3Anumber%20%3D%201%3B%5Cn%5Cn%20%20%20%20constructor(price)%20%7B%5Cn%20%20%20%20%20%20%20%20this.price%20%3D%20price%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%20%20%20%20%40computed%20get%20total()%20%7B%5Cn%20%20%20%20%20%20%20%20return%20this.price%20*%20this.amount%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%7D%7D

**Comment by jlongster** [comment]
We could maybe do it if there is a only 1 and it's decorating a property. I'm not sure about getters or functions. I thought the standard style was to put them on top.

**Comment by vjeux** [comment]
I implemented that suggestion: https://github.com/jlongster/prettier/pull/459

**Comment by hampusohlsson** [comment]
@vjeux FYI looks like [this issue still appears](https://prettier.github.io/prettier/#%7B%22content%22%3A%22import%20%7Bobservable%2C%20action%7D%20from%20%5C%22mobx%5C%22%3B%5Cn%5Cnclass%20Order%20%7B%5Cn%20%20%20%20%40observable%20price%20%3D%200%3B%5Cn%5Cn%20%20%20%20constructor(price)%20%7B%5Cn%20%20%20%20%20%20%20%20this.price%20%3D%20price%3B%5Cn%20%20%20%20%7D%5Cn%5Cn%5Ct%40action.bound%20setPrice(amount)%20%7B%5Cn%20%20%20%20%20%20%20%20this.price%20%2B%3D%20amount%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D) for MobX 3 `@action.bound` decorators

**Comment by vjeux** [comment]
@hampusohlsson do you mind making a separate issue for it, so we can track this form independently? Thanks!

**Comment by hampusohlsson** [comment]
On it!

**Comment by zh99998** [comment]
It's really ugly to put them in one line in field definition like in TypeORM.

before

```typescript
@Entity()
export class Board {
  
    @PrimaryGeneratedColumn()
    id: number;
    
    @Column()
    slug: string;
    
    @Column()
    name: string;
    
    @Column()
    theme: string;
    
    @Column()
    description: string;
    
    @OneToMany(type => Topic, topic => topic.board)
    topics: Topic[]
  
}
```

after

```typescript
@Entity()
export class Board {
  @PrimaryGeneratedColumn() id: number;

  @Column() slug: string;

  @Column() name: string;

  @Column() theme: string;

  @Column() description: string;

  @OneToMany(type => Topic, topic => topic.board)
  topics: Topic[];
}
```

**Comment by michaeljota** [comment]
Can be this be configurable? I know that prettier is an opinionated printer, but still, I fell like this could be configurable.
